---
title: "README"
author: "Alisa Röring / Sammi Johnson"
date: "2025-12-05"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# Notes

## TO-DO:
 
- Give weights to traits for multi-trait score (Which traits are more important than others)
- Find out if lower or higher plant height is best for winter rape seed
- Discuss what to do about the Flowering Times
- Write a script to calculate the multi-trait-score
- Decide what kind of PCAs we want to do
- ???


## Primary objectives:
- Evaluate multiple genotypes based on their traits
- Calculate Multi-Trait Score to assess overall performance for each genotype.
- Use PCA to visualize phenotypic or genetic variability among genotypes.
- Select three genotypes that combine:
- high performance/quality (Multi-Trait-Score) and
- High genetic diversity  (PCA)


## Multi-Trait Score
 
We wanna combine several meaningful traits into a single numerical value that reflects the overall performance of each genotype.
This score is based only on traits that show clear and significant! genetic variation.
 
### BLUP = Best Linear Unbiased Prediction
A statistical estimate of the genetic performance of a genotype. BLUPs represent the genetic value of a genotype for a trait!

Corrects for:
- environmental effects
- replicate/block effects
- random error
 
### EBLUP = Estimated BLUP
- This is simply: EBLUP = BLUP + grand mean
- BLUPs alone are centered around zero so they are sucky to read
- EBLUPs shift the predictions back to the original trait scale, making them comparable and interpretable.
- For PCA and multi-trait scoring, EBLUPs are typically used so we are doing that, too.
 

## Traits Included in the Multi-Trait Score
Only traits with a significant genotype effect (p < 0.05)
 
Included traits (BLUP/EBLUP used):
- SQI (Seed Quality Index) this I have calculated using the measured traits from the seed quality sheet they provided [Updated with Sarah's input!]
- CCM (Chlorophyll Content)
- HGW (Hundred Grain Weight)
- Fresh Mass (FM) 
  - "After sampling" was incomplete and I left it out because I didn't see the use of it.
- Dry Weight (DW)
- Plant Height (PH)
- BBCH

## Traits Excluded from the Multi-Trait Score
I excluded them because the genotype had no significant effect on the trait (Flowering Time) or because I was uncertain.
 
Flowering Type (FT): Genotype had no significant effect on flowering type


## NEW: KASP ANALYSIS

- AA -> RLM4
- CC -> RLM7 or RLM9
- AC -> Carries all 3 but we only have homozygotes I think?


## What I did so far:
 
- Extracted BLUPS and EBLUPS for the relevant traits [Update: Included Thursday Datsets]
- Calculated Means for FT 
- Put the data into an excel file for overview

## Questions (bad) :
 
- Which traits do we include in the PCAs?
- Do we include only EBLUPS in PCAs? Or can means be used from traits that have no effect on genotype? 
  - Maybe BBCH and FT for developmental PCA? DOES THAT EVEN MAKE SENSE?
- What kind of PCAs are we gonna do?
 
 
### BBCH:
- How do we handle this trait? Is it influenced strongly genetically or is it environmental?
- Is it a performance trait? Or a diversity trait? Phenological diversity vs perfomance quality?
- Is higher BBCH = Better? Or should it only be included in a developmental PCA?
- Is smaller plant height better?




## Questions (good):
(Qs I would like to answer with PCAs)
 
- Which of these traits explain most of the performance variation?
- Which genotypes perform similarly across all traits?
- Are high-scoring genotypes diverse or not? Are top-performers clustering tightly or spread out?
- Do some traits co-vary?
- Are there like.. How do you say in english? Trade-offs? Like High something but low something else?
